### ISSUE TITLE
cant upload odk script to google app engine

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1098]
Originally reported on Google Code with ID 1097
```
What steps will reproduce the problem?
I am following instructions, at http://www.google.com/earth/outreach/tutorials/odk_gettingstarted.html

but I am getting this
Looking for java... 
found java in PATH... C:\Windows\System32\java.exe 
java.lang.UnsupportedClassVersionError: com/google/appengine/tools/admin/AppCfg : Unsupported
major.minor version 51.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(Unknown Source)
at java.lang.ClassLoader.defineClass(Unknown Source)
at java.security.SecureClassLoader.defineClass(Unknown Source)
at java.net.URLClassLoader.defineClass(Unknown Source)
at java.net.URLClassLoader.access$000(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: com.google.appengine.tools.admin.AppCfg. Program will
exit.
Exception in thread "main" 
---- WEBSITE COMPLETE - BEGIN BACKEND ---- 
java.lang.UnsupportedClassVersionError: com/google/appengine/tools/admin/AppCfg : Unsupported
major.minor version 51.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(Unknown Source)
at java.lang.ClassLoader.defineClass(Unknown Source)
at java.security.SecureClassLoader.defineClass(Unknown Source)
at java.net.URLClassLoader.defineClass(Unknown Source)
at java.net.URLClassLoader.access$000(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: com.google.appengine.tools.admin.AppCfg. Program will
exit.
Exception in thread "main" 
---END-SCRIPT-SUCCESS--- 


What is the expected output? What do you see instead?

Not Able to generate the correct initial script


What version of the product are you using? On what operating system?

Windows 8 64 but

Please provide any additional information below.

```

Reported by `mohtashammm` on 2014-12-27 09:15:39

**Comment by marshallb93** [comment]
Please ask any questions such as this in the [Google group](https://groups.google.com/forum/#!forum/opendatakit).

Thanks,

Dev Team
