### ISSUE TITLE
Aggregate will not Install to App Engine

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#1155]
Originally reported on Google Code with ID 1154

```
What steps will reproduce the problem?
1. Download ODK Aggregate v1.4.7 windows-installer
2. Insert required information 
3. Run 

What is the expected output? What do you see instead?

I expect it to load on the Google project I created in Developer

What version of the product are you using? On what operating system?
v1.4.7 on Windows Vista (I know, I'm working on an upgrade, its a nonprofit, emphasis
on "non")

Please provide any additional information below.

Here is the Log: 

nable to update:
com.google.appengine.tools.admin.HttpIoException: Error posting to URL: https://appengine.google.com/api/appversion/getresourcelimits?app_id=ActiveStreetsSurveys&version=1&
400 Bad Request
Client Error (400)The request is invalid for an unspecified reason.

    at com.google.appengine.tools.admin.AbstractServerConnection.send1(AbstractServerConnection.java:336)
    at com.google.appengine.tools.admin.AbstractServerConnection.send(AbstractServerConnection.java:287)
    at com.google.appengine.tools.admin.AbstractServerConnection.post(AbstractServerConnection.java:266)
    at com.google.appengine.tools.admin.LoggingClientDeploySender.send(LoggingClientDeploySender.java:47)
    at com.google.appengine.tools.admin.ResourceLimits.remoteRequest(ResourceLimits.java:173)
    at com.google.appengine.tools.admin.ResourceLimits.request(ResourceLimits.java:139)
    at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:505)
    at com.google.appengine.tools.admin.AppAdminImpl.updateAllBackends(AppAdminImpl.java:80)
    at com.google.appengine.tools.admin.AppCfg$BackendsUpdateAction.execute(AppCfg.java:2068)
    at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:337)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:218)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:128)
    at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:124)
com.google.appengine.tools.admin.AdminException: Unable to update app: Error posting
to URL: https://appengine.google.com/api/appversion/getresourcelimits?app_id=ActiveStreetsSurveys&version=1&
400 Bad Request
Client Error (400)The request is invalid for an unspecified reason.

    at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:517)
    at com.google.appengine.tools.admin.AppAdminImpl.updateAllBackends(AppAdminImpl.java:80)
    at com.google.appengine.tools.admin.AppCfg$BackendsUpdateAction.execute(AppCfg.java:2068)
    at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:337)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:218)
    at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:128)
    at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:124)
Caused by: com.google.appengine.tools.admin.HttpIoException: Error posting to URL:
https://appengine.google.com/api/appversion/getresourcelimits?app_id=ActiveStreetsSurveys&version=1&
400 Bad Request
Client Error (400)The request is invalid for an unspecified reason.

    at com.google.appengine.tools.admin.AbstractServerConnection.send1(AbstractServerConnection.java:336)
    at com.google.appengine.tools.admin.AbstractServerConnection.send(AbstractServerConnection.java:287)
    at com.google.appengine.tools.admin.AbstractServerConnection.post(AbstractServerConnection.java:266)
    at com.google.appengine.tools.admin.LoggingClientDeploySender.send(LoggingClientDeploySender.java:47)
    at com.google.appengine.tools.admin.ResourceLimits.remoteRequest(ResourceLimits.java:173)
    at com.google.appengine.tools.admin.ResourceLimits.request(ResourceLimits.java:139)
    at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:505)
    ... 6 more

```

Reported by `ActiveStreets` on 2015-06-29 23:41:49

**Comment by jbeorse** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jeffisveryhungry@gmail.com
    Domain beorse.net has exceeded the max emails per hour (267/250 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:43332)
	by hp159.hostpapa.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-c877-jeff=beorse.net@sgmail.github.com>)
	id 1dgMCP-000eWj-JZ
	for jeff@beorse.net; Fri, 11 Aug 2017 22:30:49 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=kH1nldYS4OEDeBRmuiehA4bm0hs=; b=XkFuqW+5u16YOz+C
	qxpa+AzkizzywmHl73loZHbDfZzpT26GlsGhXfEvdAKCq0Q3OhPf9hgOmQ1kkNIs
	udAf+HVegjTxs3zNHPNSupbnJTje7onAzRUgjh0SOfs5caDRwnzIimc3h/oLehye
	LYGXU2PbDPUnNyAOBkPNE5olMZk=
Received: by filter0576p1mdw1.sendgrid.net with SMTP id filter0576p1mdw1-19803-598E682E-55
        2017-08-12 02:30:06.804554289 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0031p1mdw1.sendgrid.net (SG) with ESMTP id KghsbySSThmSrDJ8tsjZag
	for <Jeff@Beorse.net>; Sat, 12 Aug 2017 02:30:06.706 +0000 (UTC)
Date: Sat, 12 Aug 2017 02:30:07 +0000 (UTC)
