### ISSUE TITLE
Protocol error on string > 255 chars

### ISSUE THREAD

**Issue by nilesr** [opendatakit/opendatakit#1321]
Got an odd bug syncing to aggserver.southcentralus.cloudapp.azure.com as olive. It displayed the same thing in an alert dialog. 
06-05 12:14:01.216 9353-9369/org.opendatakit.services:sync E/SyncNotification: 0 FINAL SYNC Notification -default TEXT:Protocol Error.
                                                                               Please verify that the server and device are compatible.
0

Also when I dismissed the alert dialog, the "SYNC NOW" button was disabled.

06-05 12:16:50.341 9353-9421/org.opendatakit.services:sync E/HttpRestProtocolWrapper: Unexpected server response statusCode: 400
06-05 12:16:50.342 9353-9421/org.opendatakit.services:sync E/ProcessRowDataPushLocalChanges: Exception in synchronizeTable - pushing data up to server on table: registration exception: Unexpected server response status...
06-05 12:16:50.342 9353-9421/org.opendatakit.services:sync W/System.err: org.opendatakit.services.sync.service.exceptions.ServerDetectedVersionMismatchedClientRequestException: Unexpected server response statusCode: 400
06-05 12:16:50.342 9353-9421/org.opendatakit.services:sync W/System.err:     at org.opendatakit.services.sync.service.logic.HttpRestProtocolWrapper.httpClientExecute(HttpRestProtocolWrapper.java:904)
06-05 12:16:50.342 9353-9421/org.opendatakit.services:sync W/System.err:     at org.opendatakit.services.sync.service.logic.AggregateSynchronizer.pushLocalRows(AggregateSynchronizer.java:551)
06-05 12:16:50.342 9353-9421/org.opendatakit.services:sync W/System.err:     at org.opendatakit.services.sync.service.logic.ProcessRowDataPushLocalChanges.pushLocalChanges(ProcessRowDataPushLocalChanges.java:417)
06-05 12:16:50.342 9353-9421/org.opendatakit.services:sync W/System.err:     at org.opendatakit.services.sync.service.logic.ProcessRowDataOrchestrateChanges.synchronizeTableDataRowsAndAttachments(ProcessRowDataOrchestrateChanges.java:274)
06-05 12:16:50.342 9353-9421/org.opendatakit.services:sync W/System.err:     at org.opendatakit.services.sync.service.logic.ProcessRowDataOrchestrateChanges.synchronizeDataRowsAndAttachments(ProcessRowDataOrchestrateChanges.java:166)
06-05 12:16:50.342 9353-9421/org.opendatakit.services:sync W/System.err:     at org.opendatakit.services.sync.service.AppSynchronizer$SyncTask.sync(AppSynchronizer.java:302)
06-05 12:16:50.343 9353-9421/org.opendatakit.services:sync W/System.err:     at org.opendatakit.services.sync.service.AppSynchronizer$SyncTask.run(AppSynchronizer.java:174)
06-05 12:16:50.343 9353-9421/org.opendatakit.services:sync W/System.err:     at java.lang.Thread.run(Thread.java:818)
0

**Comment by nilesr** [comment]
This was caused by entering more than 255 characters in the address field. The server tries to put it in postgres and postgres throws an exception, causing the server to return a 400 error. Protocol error is just what appears on the client

**Comment by nilesr** [comment]
So I've poked around on the client side. It looks like definition.csv has each column, but it just lists the data type as "string", and it doesn't include the auxinfo that was in the actual xlsx. The server has access to the auxinfo, and I see where we could check it, but just adding a new response code for a new error isn't the best solution. There are some other files on the client side that hold the data type as well, but all of them just list "string".

**Comment by nilesr** [comment]
I've done some more thinking, and one possibility is that we could add the auxinfo to the datatype in app designer, but we would have to change how it gets parsed in services, which could be complicated. We would also have to duplicate checking in both tables and survey, unless we wanted the user to only be notified of a bad cell when they try and sync.
