### ISSUE TITLE
App crashes while opening a browser

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/opendatakit#1384]
#### Software and hardware versions 
Services, Android v6.0,

#### Problem description
App crashes in devices having no browsers installed.

![ezgif com-resize](https://user-images.githubusercontent.com/18495162/36718021-4cfe3810-1bc6-11e8-841d-bf28a0487d66.gif)

#### Steps to reproduce the problem
1. Overflow menu icon
2. Choose `Settings`
3. Open Data Kit user documentation

#### Expected behavior
App should handle this either by showing user a toast that no browser is installed or by using a webview to open urls

#### Other information 
StackTrace

```
02-27 13:52:19.227 27847-27847/org.opendatakit.services E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: org.opendatakit.services, PID: 27847
                                                                          android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://opendatakit.org/... }
                                                                              at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                                              at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
                                                                              at android.app.Activity.startActivityForResult(Activity.java:3963)
                                                                              at android.app.Activity.startActivityForResult(Activity.java:3924)
                                                                              at android.app.Activity.startActivity(Activity.java:4247)
                                                                              at android.app.Activity.startActivity(Activity.java:4215)
                                                                              at android.preference.PreferenceActivity.onHeaderClick(PreferenceActivity.java:1077)
                                                                              at android.preference.PreferenceActivity.onListItemClick(PreferenceActivity.java:1049)
                                                                              at android.app.ListActivity$2.onItemClick(ListActivity.java:319)
                                                                              at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                              at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                                              at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                                              at android.widget.AbsListView.onTouchUp(AbsListView.java:3915)
                                                                              at android.widget.AbsListView.onTouchEvent(AbsListView.java:3680)
                                                                              at android.view.View.dispatchTouchEvent(View.java:9311)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                              at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                              at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                              at android.app.Activity.dispatchTouchEvent(Activity.java:2805)
                                                                              at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                              at android.view.View.dispatchPointerEvent(View.java:9531)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4283)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4098)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3789)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3846)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                                              at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5975)
                                                                              at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5949)
                                                                              at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5910)
                                                                              at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6078)
                                                                          	at android.view.InputEventReceiver.dispatchInputE
```

**Comment by MajidSas** [comment]
It can be solved by handling ActivityNotFoundException. I'll fix it later today. It will be my first contribution.

**Comment by MajidSas** [comment]
I found that this is defined in the file **/.../xml/preferences_headers.xml** which is used by this activity **/.../activities/AppPropertiesActivity.java**
I can think of two solutions:
1. add an onClickListener to the header in the xml file, and then define the behavior in the Java file within a try-catch.
2. add a DefaultUncaughtExceptionHandler for the AppPropertiesActivity and catch the exception in it.

I tested the second solution but I think the first one will be easier and will produce better behavior.

Also, I tested this issue with API 25, and the system automatically creates a new webView. So this issue is only present on older versions.

Let me know how you want me to proceed.

**Comment by SatyamBansal** [comment]
@MajidSas I think it can be fixed by calling resoveActivity as specified by android docs (https://developer.android.com/guide/components/intents-filters.html)  before launching implicit intent , 
Here is the exact reference 
![intent](https://user-images.githubusercontent.com/19202937/36847330-f693e96a-1d83-11e8-9003-4dcac7a1edb3.png)

**Comment by MajidSas** [comment]
@SatyamBansal Thank you for letting me know. I used resolveActivity instead of handling the exception explicitly.

**Comment by jbeorse** [comment]
Resolved with https://github.com/opendatakit/services/pull/70
