### ISSUE TITLE
Tables crashes when deleting a row from Spreadsheet view

### ISSUE THREAD

**Issue by linl33** [opendatakit/opendatakit#1385]
#### Software and hardware versions 
Tables 2.0.3

#### Problem description
Tables crashes after deleting a row from Spreadsheet view. 

#### Steps to reproduce the problem
1. Open Tables Spreadsheet view
2. Choose a row
3. Click delete

#### Expected behavior
Spreadsheet view reloads without crashing.

#### Other information 
stacktrace
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 16, Size: 16
       at java.util.ArrayList.get(ArrayList.java:437)
       at org.opendatakit.database.data.BaseTable.getRowAtIndex(BaseTable.java:293)
       at org.opendatakit.database.data.UserTable.getRowAtIndex(UserTable.java:129)
       at org.opendatakit.tables.views.SpreadsheetUserTable.getRowAtIndex(SpreadsheetUserTable.java:172)
       at org.opendatakit.tables.views.TabularView.onDraw(TabularView.java:638)
       at android.view.View.draw(View.java:19308)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19311)
       at android.widget.ScrollView.draw(ScrollView.java:1739)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.buildDrawingCacheImpl(View.java:18434)
       at android.view.View.buildDrawingCache(View.java:18300)
       at android.view.View.updateDisplayListIfDirty(View.java:18119)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
       at android.view.View.updateDisplayListIfDirty(View.java:18101)
       at android.view.View.draw(View.java:18920)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.updateDisplayListIfDirty(View.java:18133)
       at android.view.View.draw(View.java:18920)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.updateDisplayListIfDirty(View.java:18133)
       at android.view.View.draw(View.java:18920)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.updateDisplayListIfDirty(View.java:18133)
       at android.view.View.draw(View.java:18920)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.updateDisplayListIfDirty(View.java:18133)
       at android.view.View.draw(View.java:18920)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at com.android.internal.policy.DecorView.draw(DecorView.java:788)
       at android.view.View.updateDisplayListIfDirty(View.java:18142)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by roychowdhuryrohit-dev** [comment]
@opendatakit-bot claim
